### PR TITLE
moved imports from *.ext* to *_* to fix warnings

### PR DESCRIPTION
**Pull request by martinbarnard**
A bunch of import warnings from _.ext._ fixed so imports are ___ instead

### CODE REVIEW

**Comment by masonicGIT** [comment]
Hey @martinbarnard - What OS are you running on and what version of Python are you using?

**Comment by martinbarnard** [comment]
Python3.4.2
Raspberry pi, linux:
Linux 21co 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux

**Comment by masonicGIT** [comment]
Thanks a lot Martin

**Comment by martinbarnard** [comment]
You may want to (re)post this on the 21co slack forums.
I'm also going to have a look at the open issues, it looks like a good way
to improve my flask-fu :)

**Comment by masonicGIT** [comment]
Awesome!

Might be cool to integrate the 21 earn button :-).

**Comment by martinbarnard** [comment]
Another pull request - I have moved the private info out of the config.py
to config.ini and excluded it from github. It also creates one on the fly
at first-run.

Todo: testing to ensure all the variables are in it :)

On 8 July 2016 at 08:59, Mason Borda notifications@github.com wrote:

> Awesome!
> 
> Might be cool to integrate the 21 earn button :-).
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/masonicGIT/21-Flask-Boilerplate/pull/32#issuecomment-231281611,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAMYzd2dNO0XzVvOR_y-qgzaWHrwZ0riks5qTeczgaJpZM4JHvZ-
> .

On 8 July 2016 at 08:59, Mason Borda notifications@github.com wrote:

> Awesome!
> 
> Might be cool to integrate the 21 earn button :-).
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/masonicGIT/21-Flask-Boilerplate/pull/32#issuecomment-231281611,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAMYzd2dNO0XzVvOR_y-qgzaWHrwZ0riks5qTeczgaJpZM4JHvZ-
> .

**Pull request merged**
